### ISSUE TITLE
Establish prior art

### ISSUE THREAD

**Issue by mattkrick** [mattkrick/cashay#1]
Start chats with @gyzerok. Even though https://github.com/gyzerok/adrenaline has a different approach, the end goal is more or less the same.

Read relay source code wrt how data is stored: https://github.com/facebook/relay/tree/master/src/store

Stay up to date on http://hueypetersen.com/, it's the best blog wrt this stuff... even if @eyston ignores my emails :sob: 

Chat with @arunoda regarding future plans for https://github.com/kadirahq/lokka. The store is different, but the API is very similar. 

Feel free to share & discuss any issues regarding GraphQL client caches here.

**Comment by gyzerok** [comment]
Hi, @mattkrick! I've read your article yesterday and its awesome. Since developing Adrenaline itself and efficient caching mechanism is a little bit hard I now do not denormalise data at all, just use memoized cache heap which I invalidate after mutations.

So I'm highly interested in what you are doing. Feel free to keep me up to date. I hope I would finish top-level API and docs for Adrenaline 1.0 soon.

**Comment by mattkrick** [comment]
@gyzerok sounds awesome. I like the simplified react wrapper you came up and am hoping to follow your lead on the react-specific stuff like query aggregation. Have you started to cross that bridge yet? I still haven't figured out how to traverse a react thee to read the statics.

**Comment by eyston** [comment]
In my defense I started a new job this week :p

Can you link me the article?

This topic definitely interests me, but I can't commit to anything near term (job is totally new tech and I'm playing catchup there).  I'm technically interested in making something that could be used in the redux ecosystem because I haven't participated there but find it fascinating to watch.  So basically I want an excuse to try it out :).

When I toyed with making a stand alone store you get a lot of progress fast then start hitting identity / unions / interfaces / collections and things get hard.  A question then becomes how much of the schema do I need client side to figure things out.  For small projects having the schema be a client dependency is probably fine, but for larger projects (e.g. facebook) it is a non-starter.  But does that matter for the target?

I actually think you can get something useful rather quickly for use with Redux by just treating GraphQL as a really smart REST endpoint.  Given a query and a normalize function you can produce data useful right now by a lot of the redux stores (I assume... again, never used it).  You don't have the fancy caching Relay does, but instead you'd cache by the query.

```js
// client
dispatch({action: 'LOAD_USER', userId: 1})

// uh, reducer? action thingy? I don't know these terms ...
case: 'LOAD_USER':
  if (cache.has(action.userId) {
    return cache.get(action.userId);
  } else {
    fetch(graphqlUrl ... etc ...)
  }
```

So you don't have the niceness of diffing queries but, again, I think this is like 50% useful and can be done right away.

If you are using components based around routing (like react-router) the number of distinct client queries you are going to have is going to be basically 1:1 with routes anyways.  So doing diffing between routes is really not all that amazingly important.

The last point is that, again, I'm technically interested in this, but I'm also really interested in trying to contribute to Relay as well.  The stuff on here is exciting : https://github.com/facebook/relay/wiki/Roadmap.  So yah, I'm torn!

/end ramble

**Comment by gyzerok** [comment]
@mattkrick yeah traversing is on my roadmap for 2.0 since it's necessary for server-rendering. Right now I do my queries on lifecycle hooks which do not execute on server. The point for 1.0 is stable top-level API.

**Comment by mattkrick** [comment]
Eyyy @eyston welcome to the party! Totally understand about playing catchup, hope the new job is treating ya well! 

>I'm torn!

No need to choose between relay & cashay. The more you know about relay internals, the better that is for me :smile:. For example, do you you (or @gyzerok) see any problems with my proposed redux store shape in #4? After poking around relay's store, I think I can provide pagination with a dramatically simplified internal structure, but would love your expert opinions in case I'm leaving out an edge case :wink:. 

If there were any way I could make relay work for me I would. Rolling my own solution is always a last resort. IMO, facebook got somethings right (graphQL, react) and something wrong (flux, jest). I don't think relay is bad, considering it was written years before redux. But now that we have redux, might as well piggyback off its subscriptions, store, and *especially* middleware (100% extendable! just think of the possibilities...).

>Can you link me the article?

https://medium.com/@matt.krick/how-to-build-a-graphql-client-cache-part-i-25e698acd8af#.qnsew3ker
(I gotcha a shoutout in there, more people need to visit your blog!)

>But does that matter for the target?

Absolutely! I followed your lead & made a babel plugin factory so the only thing that hits the client is a function expression.

 >I actually think you can get something useful rather quickly for use with Redux by just treating GraphQL as a really smart REST endpoint. 

I'm thinking about skipping this step & going straight for the diffing. That means I'll either need to extend `normalizr` or roll my own since I'll need fields, not just entities, to perform a diff. I'll decide after I can lock down the shape of the store in #4.

**Comment by mattkrick** [comment]
>traversing is on my roadmap for 2.0 since it's necessary for server-rendering

@gyzerok awesome! will it be a second package? it'd be awesome if I could use adrenaline the same way redux uses react-redux. maybe i'm dreaming :laughing:

**Comment by jeffreywescott** [comment]
Ironically, from the Meteor folks, their new project: http://www.apollostack.com/
