### ISSUE TITLE
Make support for multi-part queries easier

### ISSUE THREAD

**Issue by mattkrick** [mattkrick/cashay#47]
Use case: 

1. `cashay.mutation('createFoo')`
2. `cashay.query(getFoo)`
4. `cashay.mutation('createBarForFooResult')`
3. `cashay.query(getBarForFoo)`

Neither query needs to call the server until `foo` is returned from the first mutation. So, if the query includes a required variable & that is not present, bail without an error.

**Comment by jordanh** [comment]
Since `cashay.query()` is often placed in the `mapStateToProps()` of a component, allowing the query to continue without hitting the server nor tossing an exception would be _extremely_ useful.

I suspect the mutate then query and use in component pattern will be rather common. Interesting to explore and document patterns for folks...

**Comment by jordanh** [comment]
With v0.5.10:

![image](https://cloud.githubusercontent.com/assets/103000/15938113/c0025d9e-2e3f-11e6-841f-85eb4ad61a08.png)

Getting closer!

**Comment by mattkrick** [comment]
should be fixed in 0.5.11

**Comment by jordanh** [comment]
Same verse, same as the first :)

![image](https://cloud.githubusercontent.com/assets/103000/15952571/1d87e5c4-2e90-11e6-8a3b-acd00ca056aa.png)

If you like, test on branch? https://github.com/ParabolInc/action/tree/cashay

**Comment by mattkrick** [comment]
Ah beautiful! I'll test on the branch before getting your hopes up.
PS, I think I found an elegant solution to multi-part queries. It gone be
good

**Comment by jordanh** [comment]
I spent the entire flight to Seattle getting to know Cashay more
intimately. It's a beautiful, intricate, and useful thing. The more I poke
around, the more I like it.

My goal was to get this sort of thing working:

```javascript
import React, {Component, PropTypes} from 'react';
import uuid from 'node-uuid';
import {connect} from 'react-redux';
import {push, replace} from 'react-router-redux';
import {cashay} from 'client/client';
const SIGNIN_ACTION_CREATE_TEAM_AND_MEETING = 'create_team_and_meeting';

const graphQuery = `
  query($teamId: ID!) {
    team: getTeamById(teamId: $teamId) {
      id
    }
  }`;

const mutationHandlers = {
  createTeam: (optimisticVariables, serverData) => {
    if (optimisticVariables) {
      return null;
    }
    return serverData;
  }
};

const cashayOpts = {
  component: 'SigninSuccess',
  mutationHandlers,
  variables: { teamId: null }
};

const mapStateToProps = (state) => {
  cashayOpts.variables.teamId = state.teamId;
  return {
    team: cashay.query(graphQuery, cashayOpts)
  };
};
// @connectData(fetchData)
@connect(mapStateToProps)
export default class SigninSuccess extends Component {
  static propTypes = {
    team: PropTypes.object,
    params: PropTypes.object,
    dispatch: PropTypes.func
  }

  constructor(props) {
    super(props);
    this.state = {
      newTeamId: null,
    };
  }

  componentWillMount() {
    const {dispatch, params, team} = this.props;
    const {action} = params || {};
    switch (action) {
      case SIGNIN_ACTION_CREATE_TEAM_AND_MEETING:
        if (!team) {
          const newTeamId = uuid.v4();
          this.setState({newTeamId});
          cashay.mutate('createTeam', { variables: {
            id: newTeamId,
            name: ''
          }});
        } else {
          dispatch(replace(`/team/${team}`));
        }
      default:
        dispatch(push('/404'));
    }
  }

  render() {
    return (
      <div>
        Creating team and redirecting...
      </div>
    );
  }
}
```

One discovery I made is we cannot do this as you and I had originally wrote
it...

```javascript
  const cashayOpts = {
    component: 'SigninSuccess',
    mutationHandlers,
    variables: { teamId: uuid.v4() }
  };
```

...and expect Cashay to avoid querying the server. This is because
`requiredVariablesHaveValues()` will return true inside Cashay's `query()`
function. Because, uh, there are valid variables. Of course! Doh!

After accommodating that, I ran into something I suspect is more important:
mutations don't seem to work in this pattern (query before mutate then query).
I'm not sure _exactly_ what's going on. But I can give you some clues.

Let's walk the interesting bits of this component lifecyling:

1. `SigninSuccess` is constructed, `mapStateToProps()` is called, setting
    `teamId = null`. `cashay.query()` bails, as expected.

2. `componentWillMount()` is called. A new uuid is constructed.
    `cashay.mutate('createTeam', ...)` is called using this new uuid.

3. `_processMutationHandlers()` is called the first time, giving the
   application an opportunity for an optimistic update. My `mutationHelper`
   returns `null`. Later, when `shortenNormalizedResponse()` is called,
   `normalizedResponse.entities` is undefined which causes the mutation to
   throw an exception. No biggie. Easy fix. I patched
   `shortenNormalizedResponse()` to return if `entities` are empty. If we
   test again...

4. ... `_processMutationHandlers()` is called again by `_mutateServer()` with
   proper and good `dataFromServer`. It contains a response for the
   `createTeam` mutation. Yay!

5. However, `normalizeResponse()` within `_processMutationHandlers()` will fail
   because `createTeam` won't appear in the AST. Boo!

Some questions:

* I noticed that `buildExecutionContext()` within `_processMutationHandlers()`
  is using the AST from the cached query. This must be intentional, right?
  At what point does the mutation AST get combined with cashed query AST to
  be able to parse the server's response to the mutation? Or, should we be
  using the mutation AST all along?

* Using the above component, my `cashayDataState.variables` are always
  empty. This means `contextVars` is always empty. Even if `normalizeResponse`
  had an AST it understood how to parse, it wouldn't extract any variables
  to be later merged into Cashay's cache. Mutation variables are supposed to be
  extracted from the query string, right? When are those supposed to be
  added to `cashayDataState.variables`?

I feel these are some "empty state" bugs. Let me know how I can help!

**Comment by mattkrick** [comment]
I was working on the same part coming back to SD, I _think_ I've got something good figured out:

currently, we have to tie the junk into the view-model layer (`componentWillReceiveProps`). bleh.
Instead, the user should be able to write a single operation that has many queries, and some of them will be dependent on the results of others.
To solve this, instead of bailing on the entire server call when a required variable is undefined, it just removes that part of the query (and of course remove it entirely if nothing remains). When it removes that part, we get a `willBeComplete = false` boolean which is used internally to keep the `isComplete = false` flag on the returned result.

workflow:
queries:
getTeam(teamId: ID!)
getMeeting(meetingId: ID!)

mutations:
createTeam
createMeeting

variables = {
  teamId: '123’, // passed in from outer closure/parent component/etc
  meetingId: this.props.cashayResult && this.props.cashayResult.getTeam.meetingId // guaranteed maximum of 1 safety check
}
Edge case:

if the variable is not required, the query will complete on the first server fetch
then, the user will have to call `setVariables` from within a conditional inside `componentWillReceiveProps` or `render`, same as any other `setVariables` call.

**Comment by mattkrick** [comment]
>I noticed that buildExecutionContext() within _processMutationHandlers()
is using the AST from the cached query. This must be intentional, right?
At what point does the mutation AST get combined with cashed query AST to
be able to parse the server's response to the mutation? Or, should we be
using the mutation AST all along?

I like to think of it like `mutationAST = function(queryASTs)`. It never gets combined with the query AST, but it intersects your mutation payload with each query & sends that aggregated intersection to the server. When it comes back, it [de-namespaces](https://github.com/mattkrick/cashay/blob/master/src/Cashay.js#L418) everything so what you get back in your `mutationHandler` is the server response that you expect. Then you write how you want to modify the query. That modification is then normalized, intersected with the current state, changes invalidate queries watching the same thing, the old parts are removed & the new parts are watched. 
On a side note, facebook could *really* benefit from this. For example, some annoying person has 2 posts on your newsfeed. You click "unfollow" on the first one & it is removed, but the second one remains. Ideally, you click "unfollow" and it removes both. 

>Using the above component, my cashayDataState.variables are always
empty. This means contextVars is always empty. Even if normalizeResponse
had an AST it understood how to parse, it wouldn't extract any variables
to be later merged into Cashay's cache. Mutation variables are supposed to be
extracted from the query string, right? When are those supposed to be
added to cashayDataState.variables?

A mutation string contains 2 types of variables: query variables (for the response) and mutation variables (to perform the mutation). mutation variables should never be saved in the state since they're one and done. Query variables are. For example, if a query wants a `title` field once in english & once in spanish, we need to extract we need to refer to the variables in the current state. So, when the mutation is called, it grabs the `language` variable from the current state, includes that in your `variables` object, adds the variable definition, and then sends it off. The magic starts here: https://github.com/mattkrick/cashay/blob/master/src/Cashay.js#L379

a test case that explains things more elegantly than i can is here: https://github.com/mattkrick/cashay/blob/master/src/mutate/__tests__/namespaceMutation-tests.js#L120

**Comment by jordanh** [comment]
@mattkrick I think this will do nicely! I look forward to using it in action (pun intended).
