### ISSUE TITLE
Generated pagination queries do not include existing variable definitions

### ISSUE THREAD

**Issue by simenbrekken** [mattkrick/cashay#48]
```javascript
// Initial query sent
const flightsQuery = `
  query (
    $fromDate: String!
    $toDate: String!
    $first: Int
  ) {
    flights(
      fromDate: $fromDate
      toDate: $toDate
      first: $first
    ) {
      id
      cursor
      status
    }
  }
`

// Load more button handler
const loadMore = () => setVariables(currentVariables => ({
  ...currentVariables,
  first: currentVariables.first + 10,
}))

// Follow up query (generated)
{
  flights(
    first: 20, 
    fromDate: $fromDate, 
    toDate: $toDate, 
    after: "sk884-osl-arn-20160608"
  ) {
    id
    cursor
    status
  }
}
```

**Comment by mattkrick** [comment]
Awesome, thank you for this! Could you include the mutation payload from the client schema as well? I'll dig in & see if I can duplicate this weekend.

**Comment by simenbrekken** [comment]
@mattkrick There wasn't any, I'm not using mutations yet.

**Comment by mattkrick** [comment]
Ohhhh! I get it now, I was thinking about another place where the query is generated.
So my logic when I wrote that part was to require manually entering variable definitions. That keeps things closer to vanilla GraphQL & if variable definitions were auto-generated, then I'd have to infer what the variables were based solely on the `variables` object passed into the options. Since the AST is cached for performance reasons, you'd end up with cases like this:

```
// when the AST is initially created
variables = {};
getOptionalFoo()

// when the query is called again, this time with a foo value
variables = {foo: 1}
getOptionalFoo() // AHHH we didn't cache the variable defs because when we wrote them, we didn't see any! And now we have some variables without cached definitions!
```
Hope that makes sense. GraphQL is a stinker because it throws an error if you pass in unused `variableDefinitions`.

So, we've got a couple options here:
- Require that you write variable defs for each query. This is how it's currently designed & makes it nice for troubleshooting queries because you can cut/paste the query and options into GraphiQL.
- Require that you pass in all variables that will ever be used, even if they're `undefined` right now (eg `options = {variables: {foo: undefined}}`. This is how mutations currently works
- Recreate the variable definitions every time variables change, and then remove the ones that are unnecessary.

I think the 3rd option is probably the best, and unless I'm forgetting something, that means I can do away with having to flag the variables that are in use & deleting the unused defs, which would clean up the code a great deal!

**Comment by simenbrekken** [comment]
@mattkrick Not sure if I understood that completely but I'm already defining option 1 in my first query, the second query (generated by cashay) however leaves them out for some reason.

**Comment by mattkrick** [comment]
no worries, i got this halfway cleaned up on my flight yesterday, will finish up & push today or tomorrow. End result should be 1 fewer traversal per query, so that's always nice!

**Comment by mattkrick** [comment]
@simenbrekken if this is still an issue in v0.6.0 please let me know!

**Comment by simenbrekken** [comment]
@mattkrick Working like a charm!
