### ISSUE TITLE
SendToServer and complicate query

### ISSUE THREAD

**Issue by felix-zg** [mattkrick/cashay#71]
I'm trying to use Cashay and I have a problem with this query:
`{
    docs: allDocs{
    edges{
      node{
         id,
         docUrl,
          fullUrl
    }}
}`

this is a post call to the server:
`{allDocs{
   edges{}
}}`

This nodes didn't marked as sendToServer and they chopped off by minimizeQueryAST.
Do you have any idea what may be the problem?

**Comment by mattkrick** [comment]
i'd have to see your schema to know what's up, but it looks like you're using a relay pattern. Is `node` an interface by chance? if so, it's probably related to #29 and I'd love for you to send me an example of what you're trying to do so I can build in interface functionality. I'm not opposed to it, I just can't think of an example to build into the test schema.

Also might be worth noting that Cashay was built to avoid the complexities of the `edges, node` paradigm. If you're using it by choice, that's totally valid, but if there's something that you're trying to accomplish that requires it, I'd love to hear about it.

**Comment by felix-zg** [comment]
Here is[ my schema](https://gist.github.com/felix-zg/47c1d22c83780084e34ebfb85c35df75)

We use Python for our back-end with Graphene, and unfortunately it's the way it works.

**Comment by mattkrick** [comment]
nah, graphene doesn't have to be relay-enabled, does it? https://github.com/graphql-python/graphene/tree/master/examples/starwars

if you can adjust the [test schema](https://github.com/mattkrick/cashay/blob/master/src/__tests__/schema.js) in a way so that a query or mutation returns an interface, i'd be glad to implement them, but since leaving the relay world i haven't had a need for interfaces & sometimes wonder if their sole purpose is for relay (I love being proved wrong though!).

**Comment by mattkrick** [comment]
@felix-zg should be fixed in v0.11.3, please re-open if not

**Comment by felix-zg** [comment]
Thanks!
